# This website can help select a good color
# https://htmlcolorcodes.com/
#
# A # may be prepended to any of the color values.

[player]
# background.image = "./background.jpg"
background.color = "000000" # Does nothing if image is set
clock.color = "FF0000" # Color of the actual minute:second counter text
clock.remaining.color = "FFFFFF" # Color of the "Time Remaining" text
win.color = "89D154"
win.text = "You win!"
lose.color = "E32D2D"
lose.text = "You lose!"
video = "./museum.mp4"

[master]
background = "333333"
noise = "./ping.ogg" # Sound to play when pinging
time = 3600 # Must be a positive number in seconds
log.path = "./../../game_stats.csv" # This is optional
room.name = "Museum"

[frame]
border = "D3D3D3"
label = "D3D3D3"

[expander]
color = "D3D3D3"
hovered.color = "FFFFFF"

[button]
color = "1A1A1A"
background.color = "D3D3D3"
label.color = "1A1A1A"

[entry]
background.color = "D3D3D3"
text.color = "1A1A1A"

[hint]
default.amount = 5
remaining.color = "FFFFFF" # Color of "Hints Remaining" text
amount.color = "FF0000" # Color of the number next to "Hints Remaining: "
color = "FFFFFF" # Color of the hints when they appear
select.color = "4FC6E0" # Color of the hint when its selected in the hint menu
